### ISSUE TITLE
topaz convert fails with large number of box files

### ISSUE THREAD

**Issue by olibclarke** [tbepler/topaz#13] opened 2019-03-29 15:47 UTC
When I run `topaz convert` with a small number of crYOLO box files as input, it works fine. When I run with a large number (picking a few particle on each of several thousand mics using the following command), I get the attached error message.

`topaz convert -s 16 --from box --to star *box -o particles_downscaled.star`

Cheers
Oli
<img width="983" alt="image" src="https://user-images.githubusercontent.com/19766818/55244835-53322a00-5218-11e9-8af9-2d67ac185293.png">

**Comment by olibclarke** [comment] 2019-03-29 16:20
I tested further - this seems to happen with any number of box files greater than ~200

**Comment by tbepler** [comment] 2019-03-29 16:53
Interesting. Based on the error you posted above, it doesn't seem to have anything to do with the number of files. Instead, it looks like one of the files is misformatted and causes convert to crash when it gets to that file. Is it possible to pinpoint which file is causing the error? It's possible that this is caused by an empty box file.

Making these kinds of error messages more informative on the user end is an ongoing effort.

**Comment by olibclarke** [comment] 2019-03-29 16:56
Now that I look, there are indeed a handful of empty box files... I will check if convert works if these are removed. Thanks for the quick response!

**Comment by olibclarke** [comment] 2019-03-29 17:00
Can confirm - it works when the empty box files are removed. It might be good if topaz ignored empty box files in such a circumstance to avoid the error?

**Comment by tbepler** [comment] 2019-03-29 17:12
Agreed, that needs to be fixed. Glad you have a workaround for now, though.

**Comment by tbepler** [comment] 2019-03-29 17:45
Fixed in cb2f7ab5340bd3ac06ecfa71d6cfe500ac2ab3ff

**Closed by tbepler** 2019-03-29 17:45 UTC
Labels: bug
