### ISSUE TITLE
segfault from denoising

### ISSUE THREAD

**Issue by simonbyrne** [tbepler/topaz#34] opened 2019-07-20 05:51 UTC
I'm getting the following error on 0.2.1:
```
(topaz) bash-4.2$ topaz denoise MotionCorr/job002/Micrographs/KJ071819_43-1_12_19_43.mrc -o MotionCorr/job002/Micrographs/denoise_all/
# using device=0 with cuda=False
# using model: L2
Segmentation fault (core dumped)
```

These images were collected on a K3 (which are rectangular instead of square). It worked fine for previous images collected on a K2 and Falcon 3.

**Comment by alexjnoble** [comment] 2019-07-20 20:26
Hi Simon,

The issue is almost certainly due to the GPU ram not being big enough to load the full image. Add the following to your command to denoise in chunks:

--patch-size 2048

Also, denoising works better on non-frame aligned images.

Let us know if this works!
Best regards,
-Alex

**Comment by simonbyrne** [comment] 2019-07-21 02:53
That did seem to work thanks!

**Comment by simonbyrne** [comment] 2019-07-21 03:25
Can I use tif image stack with the `--stack` option?

**Comment by tbepler** [comment] 2019-07-22 19:16
Stack only supports mrc files right now. It's sort of experimental and was originally intended for denoising particle stacks, so it just writes out a new stack with each image denoised. If you're looking for an option that will sum and denoise your frames in one step, we don't have support for that at the moment. It's something I'll probably add in the next topaz release.

**Comment by tbepler** [comment] 2019-07-26 17:13
I'm going to close this issue. If you have any follow up questions feel free to open a new one.

**Closed by tbepler** 2019-07-26 17:13 UTC
