### ISSUE TITLE
Installation problem and presence of Unet-3d-10a in v0.2.4

### ISSUE THREAD

**Issue by dgvjay** [tbepler/topaz#54] opened 2020-06-01 01:22 UTC
Hi Topaz creators and community. 

I have just started using Topaz for cryoET and ran into an installation problem. 

I installed Topaz into my conda environment and installation went well but after I activate my Topaz environment, it does not seem to recognize Topaz commands. A screenshot is attached. I guess something is wrong with my [conda?](url
![Topaz Installation problem](https://user-images.githubusercontent.com/21369792/83367886-9e3f5400-a36b-11ea-81ea-ca37a978b4c1.png)
)

Another question is regarding the presence of Unet-3d-10a in v0.2.4. I guess using the 
-m Unet-3d-10a should suffice or do we need to currently download this model from somewhere else? 

Thanks for the software and your support. 

Cheers,

**Comment by tbepler** [comment] 2020-06-01 01:31
It looks like you still need to install Topaz into your conda environment. There are instructions [here](https://github.com/tbepler/topaz#install-topaz), but the gist of it is that you need to run 
```
conda install topaz -c tbepler -c pytorch
```
from within your Topaz environment.

All of the pretrained models, including unet-3d-10a, are bundled with the topaz package so they will be installed automatically.

**Comment by dgvjay** [comment] 2020-06-01 02:14
Ohh, damn. I had a terrible brain-freeze. I created the topaz environment but did not install anything in it. Extremely sorry about that. 

Thanks!

**Comment by tbepler** [comment] 2020-06-01 03:09
No worries! I am going to close this issue since it sounds like the problem is resolved.

**Closed by tbepler** 2020-06-01 03:09 UTC
