### ISSUE TITLE
error upon launching topaz

### ISSUE THREAD

**Issue by shabihshakeel** [tbepler/topaz#30] opened 2019-07-04 11:01 UTC
Hi,

I installed using pip. Upon running topaz -h I get following error:
Traceback (most recent call last):
  File "/lmb/home/palcon/.local/bin//topaz", line 10, in <module>
    sys.exit(main())
  File "/lmb/home/palcon/.local/lib/python2.7/site-packages/topaz/main.py", line 62, in main
    import topaz.commands.extract
  File "/lmb/home/palcon/.local/lib/python2.7/site-packages/topaz/commands/extract.py", line 16, in <module>
    from topaz.algorithms import non_maximum_suppression, match_coordinates
  File "/lmb/home/palcon/.local/lib/python2.7/site-packages/topaz/algorithms.py", line 4, in <module>
    from scipy.optimize import linear_sum_assignment
ImportError: cannot import name linear_sum_assignment

Regards,
Shabih

**Comment by tbepler** [comment] 2019-07-04 17:11
I'm not able to reproduce this on my end with a fresh python 2.7 environment. I suspect the problem is due to having a  too old version of scipy installed. Can you tell me what version you have? You can find this by running "pip list" and finding the scipy line.

**Comment by tbepler** [comment] 2019-07-04 17:15
It looks like linear_sum_assignment was added in scipy v0.17.0, so make sure that your scipy version is at least that.

**Comment by tbepler** [comment] 2019-07-14 21:07
I'm going to assume that updating your scipy version fixed the issue and close this issue. If the problem persists, feel free to reopen.

**Closed by tbepler** 2019-07-14 21:07 UTC
